FROM oven/bun:latest

WORKDIR /app

COPY package*.json ./
COPY bun.lock ./
RUN bun install

RUN bun add -d tailwindcss postcss autoprefixer

COPY tailwind.config.js ./

EXPOSE 3000

CMD ["bun", "run", "dev"]