export interface Channel {
  author: string;
  authorId: string;
  authorUrl: string;
  authorBanners: AuthorBanner[];
  authorThumbnails: AuthorThumbnail[];
  subCount: number;
  totalViews: number;
  joined: number;
  autoGenerated: boolean;
  ageGated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  allowedRegions: string[];
  tabs: string[];
  tags: string[];
  authorVerified: boolean;
  latestVideos: LatestVideo[];
  relatedChannels: any[];
}

export interface AuthorBanner {
  url: string;
  width: number;
  height: number;
}

export interface AuthorThumbnail {
  url: string;
  width: number;
  height: number;
}

export interface LatestVideo {
  type: string;
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  videoThumbnails: VideoThumbnail[];
  description: string;
  descriptionHtml: string;
  viewCount: number;
  viewCountText: string;
  published: number;
  publishedText: string;
  lengthSeconds: number;
  liveNow: boolean;
  premium: boolean;
  isUpcoming: boolean;
  isNew: boolean;
  is4k: boolean;
  is8k: boolean;
  isVr180: boolean;
  isVr360: boolean;
  is3d: boolean;
  hasCaptions: boolean;
}

export interface VideoThumbnail {
  quality: string;
  url: string;
  width: number;
  height: number;
}

export interface SearchResultItem {
  type: string;
  title?: string;
  videoId?: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  videoThumbnails?: VideoThumbnail[];
  description: string;
  descriptionHtml: string;
  viewCount?: number;
  viewCountText?: string;
  published?: number;
  publishedText?: string;
  lengthSeconds?: number;
  liveNow?: boolean;
  premium?: boolean;
  isUpcoming?: boolean;
  isNew?: boolean;
  is4k?: boolean;
  is8k?: boolean;
  isVr180?: boolean;
  isVr360?: boolean;
  is3d?: boolean;
  hasCaptions?: boolean;
  authorThumbnails?: AuthorThumbnail[];
  autoGenerated?: boolean;
  subCount?: number;
  videoCount?: number;
  channelHandle?: string;
}

export interface Channel {
  author: string;
  authorId: string;
  authorUrl: string;
  authorBanners: AuthorBanner[];
  authorThumbnails: AuthorThumbnail[];
  subCount: number;
  totalViews: number;
  joined: number;
  autoGenerated: boolean;
  ageGated: boolean;
  isFamilyFriendly: boolean;
  description: string;
  descriptionHtml: string;
  allowedRegions: string[];
  tabs: string[];
  tags: string[];
  authorVerified: boolean;
  latestVideos: LatestVideo[];
  relatedChannels: any[];
}

export interface AuthorBanner {
  url: string;
  width: number;
  height: number;
}

export interface LatestVideo {
  type: string;
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorVerified: boolean;
  videoThumbnails: VideoThumbnail[];
  description: string;
  descriptionHtml: string;
  viewCount: number;
  viewCountText: string;
  published: number;
  publishedText: string;
  lengthSeconds: number;
  liveNow: boolean;
  premium: boolean;
  isUpcoming: boolean;
  isNew: boolean;
  is4k: boolean;
  is8k: boolean;
  isVr180: boolean;
  isVr360: boolean;
  is3d: boolean;
  hasCaptions: boolean;
}

export interface Playlist {
  type: string;
  title: string;
  playlistId: string;
  playlistThumbnail: string;
  author: string;
  authorId: string;
  authorUrl: string;
  subtitle: any;
  authorThumbnails: AuthorThumbnail[];
  description: string;
  descriptionHtml: string;
  videoCount: number;
  viewCount: number;
  updated: number;
  isListed: boolean;
  videos: Video[];
}

export interface Video {
  type: string;
  title: string;
  videoId: string;
  author: string;
  authorId: string;
  authorUrl: string;
  videoThumbnails: VideoThumbnail[];
  index: number;
  lengthSeconds: number;
  liveNow: boolean;
}
